//Not logged in
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const GET_MESSAGE_BY_ID = 'GET_MESSAGE_BY_ID';
export const GET_MESSAGE_BY_CONTENT = 'GET_MESSAGE_BY_CONTENT';
export const GET_MESSAGE_BY_CONTENT_AND_CATEGORIE = 'GET_MESSAGE_BY_CONTENT_AND_CATEGORIE';
export const POST_COMMENT_BY_MESSAGE_ID = 'POST_COMMENT_BY_MESSAGE_ID';

//Logged in
export const UPVOTE_BY_MESSAGE_ID = 'UPVOTE_BY_MESSAGE_ID';
export const DOWNVOTE_BY_MESSAGE_ID = 'DOWNVOTE_BY_MESSAGE_ID';

//API Calls
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';
export const FETCH_COMMENTS_BY_ID_SUCCESS = 'FETCH_COMMENTS_BY_ID_SUCCESS';
export const FETCH_COMMENTS_BY_ID_FAILURE = 'FETCH_COMMENTS_BY_ID_FAILURE';
export const UPVOTE_MESSAGE_SUCCESS = 'UPVOTE_MESSAGE_SUCCESS';
export const UPVOTE_MESSAGE_FAILURE = 'UPVOTE_MESSAGE_FAILURE';
export const DOWNVOTE_MESSAGE_SUCCESS = 'DOWNVOTE_MESSAGE_SUCCESS';
export const DOWNVOTE_MESSAGE_FAILURE = 'DOWNVOTE_MESSAGE_FAILURE';